# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Pay-As-You-Go(7065e8b0-8cf7-4e1e-ad88-a04542f800da)'
    azureContainerRegistry: '{"loginServer":"adamazureacr.azurecr.io", "id" : "/subscriptions/7065e8b0-8cf7-4e1e-ad88-a04542f800da/resourceGroups/container-registery-rg/providers/Microsoft.ContainerRegistry/registries/adamazureacr"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'