stages:
- stage: Build
  jobs:
  - job: Build
    trigger:
    - master

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'adamazureacr'
        repository: 'examplewebapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
- stage: Deploy
  jobs:
    # track deployments on the environment
  - deployment: DeployWeb
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn’t exist
    environment: 'smarthotel-dev'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment